import carouselStory from './core-ui/carouselStory';
import categoryItemStory from './core-ui/categoryItemStory';
import datePickerStory from './core-ui/DatePicker';
import discountBadgeStory from './core-ui/discountBadgeStory';
import richRadioGroupStory from './core-ui/richRadioGroupStory';
import searchInputStory from './core-ui/searchInputStory';
import stepIndicatorStory from './core-ui/stepIndicatorStory';
import surfaceStory from './core-ui/surfaceStory';
import tabStory from './core-ui/tabStory';

import manageAddressStory from './components/manageAddressStory';
import checkoutAddressStory from './components/checkOutAddressStory';
import orderHistoryItemStory from './components/orderHistoryItemStory';
import orderItemStory from './components/orderItemStory';
import productItemStory from './components/productItemStory';

manageAddressStory();
checkoutAddressStory();
carouselStory();
categoryItemStory();
datePickerStory();
discountBadgeStory();
orderHistoryItemStory();
orderItemStory();
productItemStory();
richRadioGroupStory();
searchInputStory();
stepIndicatorStory();
surfaceStory();
tabStory();
