import checkoutAddressStory from './components/checkOutAddressStory';
import manageAddressStory from './components/manageAddressStory';
import orderHistoryItemStory from './components/orderHistoryItemStory';
import orderItemStory from './components/orderItemStory';
import productItemStory from './components/productItemStory';
import productListStory from './components/productListStory';
import avatarStory from './core-ui/avatarStory';
import carouselStory from './core-ui/carouselStory';
import categoryListStory from './core-ui/categoryListStory';
import discountBadgeStory from './core-ui/discountBadgeStory';
import modalBottomSheetStory from './core-ui/modalBottomSheetStory';
import richRadioGroupStory from './core-ui/richRadioGroupStory';
import searchInputStory from './core-ui/searchInputStory';
import surfaceStory from './core-ui/surfaceStory';
import tabStory from './core-ui/tabStory';
import toastStory from './core-ui/toastStory';

toastStory();
avatarStory();
carouselStory();
discountBadgeStory();
productItemStory();
richRadioGroupStory();
searchInputStory();
surfaceStory();
tabStory();
modalBottomSheetStory();
productListStory();
categoryListStory();
manageAddressStory();
checkoutAddressStory();
orderHistoryItemStory();
orderItemStory();
