import carouselStory from './core-ui/carouselStory';
import discountBadgeStory from './core-ui/discountBadgeStory';
import tabStory from './core-ui/tabStory';
import surfaceStory from './core-ui/surfaceStory';
import stepIndicatorStory from './core-ui/stepIndicatorStory';
import datePickerStory from './core-ui/DatePicker';
import categoryItemStory from './core-ui/categoryItemStory';
import productItemStory from './component/productItemStory';
import orderItemStory from './component/orderItemStory';
import orderHistoryItemStory from './component/orderHistoryItemStory';
import searchInputStory from './core-ui/searchInputStory';

carouselStory();
discountBadgeStory();
orderItemStory();
surfaceStory();
tabStory();
stepIndicatorStory();
productItemStory();
datePickerStory();
orderHistoryItemStory();
searchInputStory();
categoryItemStory();
