export const COLORS = {
  white: '#FFFFFF',
  darkWhite: '#FAFAFA',
  black: '#2D2D2D',
  red: '#FF5852',
  orange: '#FF5C5C',
  grey: '#A4A4A4',
  priceGrey: '#C4C4C4',
  lightGrey: '#E8E8E8',
  primaryColor: '#0253B3',
  stepIndicatorLabel: '#0458BD',
  stepIndicator: '#0050B6',
  orderStatusDelivered: '#63CE05',
  orderStatusOnProcess: '#64B1FF',
  wishlist: '#FF4A88',
  transparent: 'transparent',
  inactive: '#AAAAAA',
};
